# permissions for end users to edit modelroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aiengine
    app.kubernetes.io/managed-by: kustomize
  name: modelroute-editor-role
rules:
- apiGroups:
  - ai.kmesh.net
  resources:
  - modelroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.kmesh.net
  resources:
  - modelroutes/status
  verbs:
  - get
