---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ai.kmesh.net
  resources:
  - targetmodels
  - virtualmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ai.kmesh.net
  resources:
  - targetmodels/finalizers
  - virtualmodels/finalizers
  verbs:
  - update
- apiGroups:
  - ai.kmesh.net
  resources:
  - targetmodels/status
  - virtualmodels/status
  verbs:
  - get
  - patch
  - update
