# permissions for end users to view virtualmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aiengine
    app.kubernetes.io/managed-by: kustomize
  name: virtualmodel-viewer-role
rules:
- apiGroups:
  - ai.kmesh.net
  resources:
  - virtualmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.kmesh.net
  resources:
  - virtualmodels/status
  verbs:
  - get
