apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiengine
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiengine
  template:
    metadata:
      labels:
        app: aiengine
    spec:
      serviceAccountName: aiengine
      containers:
        - name: aiengine
          image: ghcr.io/yaozengzeng/aiengine:latest
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: aiengine
  namespace: ollama
spec:
  selector:
    app: aiengine
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aiengine
    app.kubernetes.io/managed-by: kustomize
  name: aiengine
  namespace: ollama
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-role
  namespace: ollama
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  namespace: ollama
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: aiengine
    namespace: ollama
---

