apiVersion: ai.kmesh.net/v1alpha1
kind: AIExtension
metadata:
  name: ai-extensions
  namespace: ollama
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ollama
  options:
    rateLimits:
    - requestsPerUnit: 10
      unit: MINUTE
      model: llama3.2
