apiVersion: ai.kmesh.net/v1alpha1
kind: AIExtension
metadata:
  name: ai-extensions
  namespace: ollama
spec:
  hostname: www.ollama.com
  options:
    rateLimits:
      - tokensPerUnit: 10
        unit: minute
        model: llama3.2
