apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: ext-proc-example
  namespace: ollama
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ollama
  extProc:
  - backendRefs:
    - name: aiengine
      port: 9002
    processingMode:
      request:
        body: Buffered
      response:
        body: Buffered
