apiVersion: ai.kmesh.net/v1alpha1
kind: ModelRoute
metadata:
  name: deepseek
  namespace: ollama
spec:
  modelName: "deepseek-r1"
  ruels:
  - name: "premium"
    modelMatches:
    - headers:
      user-type:
        exact: premium
    targetModels:
    - name: "deepseek-r1-7b"
  - name: "default"
    targetModels:
    - name: "deepseek-r1-1-5b"
