apiVersion: ai.kmesh.net/v1alpha1
kind: ModelServer
metadata:
  name: deepseek-r1-7b
  namespace: ollama
spec:
  workloadSelector:
    matchLabels:
      app: deepseek-r1-7b
  model: "deepseek-r1:7b"
  inferenceEngine: "sglang"
  trafficPolicy:
    timeout: 10s
