apiVersion: ai.kmesh.net/v1alpha1
kind: ModelRoute
metadata:
  name: deepseek
  namespace: ollama
spec:
  modelName: "deepseek-r1"
  ruels:
  - name: "deepseek-r1-route"
    targetModels:
    - name: "deepseek-r1-7b"
      weight: 70
    - name: "deepseek-r1-7b"
      weight: 30
