apiVersion: ai.kmesh.net/v1alpha1
kind: ModelServer
metadata:
  name: deepseek-r1-1-5b
  namespace: ollama
spec:
  workloadSelector:
    matchLabels:
      app: deepseek-r1-1-5b
  model: "deepseek-r1:1.5b"
  trafficPolicy:
    timeout: 10s
