apiVersion: ai.kmesh.net/v1alpha1
kind: TargetModel
metadata:
  name: deepseek-r1-1-5b
  namespace: ollama
spec:
  workloadSelector:
    matchLabels:
      app: deepseek-r1-1-5b
  name: "deepseek-r1:1.5b"
  trafficPolicy:
    timeout: 10s
  subsets:
  - name: "v1"
    labels:
      version: v1
  - name: "v2"
    labels:
      version: v2
