apiVersion: ai.kmesh.net/v1alpha1
kind: TargetModel
metadata:
  name: deepseek
  namespace: ollama
spec:
  workloadSelector:
    matchLabels:
      app: ollama
  name: "deepseek-r1:1.5b"
  # hostname: "http://ollama.ollama.svc.cluster.local:11434"
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  # subsets:
  # - name: v1
  #   labels:
  #     version: v1
  #   trafficPolicy:
  #     ...
  # loras:
  # - name: lora1
  #   trafficPolicy:
  #     ...
