apiVersion: ai.kmesh.net/v1alpha1
kind: VirtualModel
metadata:
  name: llama
  namespace: ollama
spec:
  models:
  - "deepseek-r1"
  rateLimit:
    tokensPerUnit: 10
    unit: minute
  rules:
  - name: "deepseek-r1-route"
  # match: 
    route:
    - destination:
        targetModel: "deepseek-r1:1.5b"
        #lora: deepseek-r1-lora1
        #subset: v1
      weight: 70
    - destination:
        targetModel: "deepseek-r1:7b"
      weight: 30
    timeout: 10s
    retries:
      attempts: 3
