apiVersion: ai.kmesh.net/v1alpha1
kind: VirtualModel
metadata:
  name: llama
  namespace: ollama
spec:
  models:
  - "deepseek-r1:1.5b"
  rateLimit:
    tokensPerUnit: 10
    unit: minute
  rules:
  - name: "deepseek-r1-route"
  # match: 
    route:
    - destination:
        host: "http://ollama.ollama.svc.cluster.local:11434"
        model: "ollama/deepseek-r1:1.5b"
      weight: 70
    - destination:
        host: "http://ollama.ollama-test.svc.cluster.local:11434"
        model: "ollama/deepseek-r1:7b"
      weight: 30
    timeout: 10s
    retries:
      attempts: 3
