apiVersion: ai.kmesh.net/v1alpha1
kind: VirtualModel
metadata:
  name: llama
  namespace: ollama
spec:
  models:
  - "llama"
  rules:
  - name: "llama-route-32"
  # match: 
    route:
    - destination:
        host: "http://ollama.ollama.svc.cluster.local:11434"
        model: "ollama/llama3.2"
      weight: 70
    - destination:
        host: "http://ollama.ollama-test.svc.cluster.local:11434"
        model: "ollama/llama3.2"
      weight: 30
    timeout: 10s
    retries:
      attempts: 3
