apiVersion: ai.kmesh.net/v1alpha1
kind: VirtualModel
metadata:
  name: llama
  namespace: ollama
spec:
  models:
  - "llama"
  rules:
  - name: "llama-route-32"
  # match: 
    route:
    - destination:
        host: ollama.ollama.svc.cluster.local
        model: "ollama/llama:3.2"
      weight: 70
    - destination:
        host: ollama.ollama-test.svc.cluster.local
        model: "ollama/llama:3.2"
      weight: 30

